name: show-directory

on: push
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
      
      - run: make setup
             make start
         
      - name: run tests
        run: make test 

      - run: make lint